### ISSUE TITLE
Can you transfer repo ? or I made PR ?

### ISSUE THREAD

**Issue by zckrs** [akameco/eslint-config-xo-react-space#1]
Hi,

I just create a repo like you https://github.com/zckrs/eslint-config-xo-react-space

And I see you have already publish on NPM.

The main diff between the two repo (you and me) I used the same structure of eslint-config-xo-space 

https://github.com/zckrs/eslint-config-xo-react-space/blob/master/index.js

**Comment by akameco** [comment]
Your code is good :+1: 
Please PR.

**Comment by zckrs** [comment]
@akameco I'm sorry I try to use scoped package and I publish on NPM by accident.

A related issue https://github.com/sindresorhus/eslint-config-xo-react/issues/7

**Comment by akameco** [comment]
Oh, eslint-config-xo-react supported space.
That's good!

**Comment by zckrs** [comment]
Yep since 1 hour ^^
